# Generated by Django 5.2.8 on 2026-02-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('current_stock', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('min_stock', models.FloatField()),
                ('max_stock', models.FloatField()),
                ('last_restocked', models.CharField(default='Today', max_length=100)),
                ('status', models.CharField(choices=[('good', 'Good'), ('low', 'Low Stock'), ('critical', 'Critical')], default='good', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Mains', 'Mains'), ('Starters', 'Starters'), ('Beverages', 'Beverages'), ('Breads', 'Breads'), ('Desserts', 'Desserts')], default='Mains', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'On Duty'), ('off', 'Off Duty')], default='active', max_length=20)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('checkin_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('billed', 'Bill Printed')], default='available', max_length=20)),
                ('current_guests', models.IntegerField(blank=True, null=True)),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('items_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
