# Generated by Django 5.2.8 on 2026-02-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
