# Generated by Django 5.2.8 on 2026-02-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_category_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
