# Generated by Django 5.2.8 on 2026-02-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_table_qr_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='in_stock',
        ),
    ]
