# Generated by Django 5.2.8 on 2026-03-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_menuitem_has_variants_menuitemvariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemvariant',
            old_name='menu_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='menuitemvariant',
            old_name='name',
            new_name='size_name',
        ),
        migrations.AlterField(
            model_name='menuitemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
